version: "3.9"

services:
  synapsis-test:
    container_name: synapsis-test
    build: .
    environment:
      - DATABASE_URL= "host=localhost, user=postgres, password=root, dbname=synapsis-test, sslmode=disable"
    ports:
      - 8080:8080
    depends_on:
      - postgresql
      - redis
  postgresql:
    container_name: postgresql
    image: postgres:12
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: synapsis-test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    ports:
      - "6000:6000"

volumes:
  pgdata: {}
